# Generated by Django 4.1 on 2024-02-06 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satsangdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CountySel', models.CharField(max_length=50)),
                ('StateSel', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 14, 48, 15, 612400))),
            ],
        ),
        migrations.DeleteModel(
            name='Statedata',
        ),
    ]
