# Generated by Django 4.1 on 2024-02-08 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_speakers_alter_satsangdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satsangdata',
            old_name='CountySel',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='satsangdata',
            old_name='StateSel',
            new_name='Satsang',
        ),
        migrations.AlterField(
            model_name='satsangdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 34, 2, 401114)),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='a_Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 34, 2, 401114)),
        ),
    ]
