# Generated by Django 4.1 on 2024-02-12 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_countysel_satsangdata_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speakers',
        ),
        migrations.AddField(
            model_name='satsangdata',
            name='Phonenumber',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='satsangdata',
            name='Place',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satsangdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 19, 3, 47, 315039)),
        ),
    ]
