# Generated by Django 4.1 on 2024-02-12 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_speakers_satsangdata_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satsangdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 19, 6, 29, 865928)),
        ),
        migrations.AlterField(
            model_name='satsangdata',
            name='Phonenumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='satsangdata',
            name='Place',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
