# Generated by Django 3.2.23 on 2024-02-26 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_satsangdata_date_alter_satsangdata_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satsangdata',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
