# Generated by Django 3.2.23 on 2024-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_satsangdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satsangdata',
            name='Date',
            field=models.DateField(),
        ),
    ]
