# Generated by Django 3.2.23 on 2024-02-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_satsangdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satsangdata',
            name='Place',
        ),
    ]
